# Generated by Django 2.2rc1 on 2019-03-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages_plus', '0004_auto_20171214_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='name_sv',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
